export const categoriesOpt = [
  { value: "Eid Specials", label: "Eid Specials" },
  { value: "Breakfast", label: "Breakfast" },
  { value: "Express", label: "Express" },
  { value: "Favourites!", label: "Favourites!" },
  { value: "Pithas", label: "Pithas" },
  { value: "Under 250!", label: "Under 250!" },
  { value: "Healthy", label: "Healthy" },
  { value: "Drinks", label: "Drinks" },
  { value: "Kebab", label: "Kebab" },
  { value: "Dessert", label: "Dessert" },
  { value: "Baked", label: "Baked" },
  { value: "Cakes", label: "Cakes" },
  { value: "Tiffin", label: "Tiffin" },
  { value: "For 1", label: "For 1" },
  { value: "Biryani", label: "Biryani" },
  { value: "Curry", label: "Curry" },
  { value: "Platter", label: "Platter" },
  { value: "Spicy Foods", label: "Spicy Foods" },
  { value: "Dawat", label: "Dawat" },
  { value: "Achar &amp; Sauce", label: "Achar &amp; Sauce" },
  { value: "Groceries", label: "Groceries" },
  { value: "Pitha", label: "Pitha" },
];
export const tagsOpt = [
  { label: "Afghani", value: "Afghani" },
  { label: "American", value: "American" },
  { label: "Appetizer", value: "Appetizer" },
  { label: "Arabic", value: "Arabic" },
  { label: "Argentinian", value: "Argentinian" },
  { label: "Asian", value: "Asian" },
  { label: "Baby Food", value: "Baby Food" },
  { label: "Bakery", value: "Bakery" },
  { label: "Bangali", value: "Bangali" },
  { label: "Bangali Chinese", value: "Bangali Chinese" },
  { label: "Brazilian", value: "Brazilian" },
  { label: "British", value: "British" },
  { label: "Burmese", value: "Burmese" },
  { label: "Caribbean", value: "Caribbean" },
  { label: "Chatgaya", value: "Chatgaya" },
  { label: "Chinese", value: "Chinese" },
  { label: "Condiment", value: "Condiment" },
  { label: "Continental", value: "Continental" },
  { label: "CookupsFit", value: "CookupsFit" },
  { label: "CookupsX", value: "CookupsX" },
  { label: "Dessert", value: "Dessert" },
  { label: "Dhakaiya", value: "Dhakaiya" },
  { label: "Drink", value: "Drink" },
  { label: "Eastern European", value: "Eastern European" },
  { label: "Ethiopian", value: "Ethiopian" },
  { label: "European (Other)", value: "European (Other)" },
  { label: "Filipino", value: "Filipino" },
  { label: "French", value: "French" },
  { label: "Fusion", value: "Fusion" },
  { label: "German", value: "German" },
  { label: "Greek", value: "Greek" },
  { label: "Growups", value: "Growups" },
  { label: "Healthy", value: "Healthy" },
  { label: "Indian", value: "Indian" },
  { label: "Indonesian", value: "Indonesian" },
  { label: "Italian", value: "Italian" },
  { label: "Japanese", value: "Japanese" },
  { label: "Keto-Friendly", value: "Keto-Friendly" },
  { label: "Kids", value: "Kids" },
  { label: "Korean", value: "Korean" },
  { label: "Lebanese", value: "Lebanese" },
  { label: "Lo-carb", value: "Lo-carb" },
  { label: "Malay/Indonesian", value: "Malay/Indonesian" },
  { label: "Malaysian", value: "Malaysian" },
  { label: "Maldivian", value: "Maldivian" },
  { label: "Mediterranean", value: "Mediterranean" },
  { label: "Mexican", value: "Mexican" },
  { label: "Middle-Eastern", value: "Middle-Eastern" },
  { label: "Mongolian", value: "Mongolian" },
  { label: "Mughlai", value: "Mughlai" },
  { label: "Nepalese", value: "Nepalese" },
  { label: "North African", value: "North African" },
  { label: "Other", value: "Other" },
  { label: "Pakistani", value: "Pakistani" },
  { label: "Paleo-Friendly", value: "Paleo-Friendly" },
  { label: "Pet Food", value: "Pet Food" },
  { label: "Puerto Rican", value: "Puerto Rican" },
  { label: "Punjabi", value: "Punjabi" },
  { label: "Russian", value: "Russian" },
  { label: "Salad", value: "Salad" },
  { label: "Shahi", value: "Shahi" },
  { label: "Singaporean", value: "Singaporean" },
  { label: "Snack", value: "Snack" },
  { label: "Snacks", value: "Snacks" },
  { label: "South American", value: "South American" },
  { label: "South Asian", value: "South Asian" },
  { label: "South East Asian", value: "South East Asian" },
  { label: "South Indian", value: "South Indian" },
  { label: "Spanish", value: "Spanish" },
  { label: "Sri Lankan", value: "Sri Lankan" },
  { label: "Swedish", value: "Swedish" },
  { label: "Sylheti", value: "Sylheti" },
  { label: "Thai", value: "Thai" },
  { label: "Turkish", value: "Turkish" },
  { label: "Vegan", value: "Vegan" },
  { label: "Vegetarian", value: "Vegetarian" },
  { label: "Vietnamese", value: "Vietnamese" },
  { label: "West Bengali", value: "West Bengali" },
  { label: "Whole 30", value: "Whole 30" },
];
